name: GitHub Readme Update

on:
  push:
    branches:
      - main
  workflow_dispatch: # Elle de tetikleyebil

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu klonla
      uses: actions/checkout@v4

    - name: Node.js kur
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Gereksiz dosya var mı kontrol et
      run: |
        echo "Her şey temiz! Profil README güncellendi."
